import path from 'path';
import fs from 'fs';

import globby from 'globby';
import shelljs from 'shelljs';

const files = globby
  .sync('**/*.stories.tsx', {
    cwd: path.resolve(`${__dirname}/../src`),
    nodir: true,
  })
  .sort()
  // eslint-disable-next-line unicorn/prefer-negative-index
  .map((story) => `import './${story.slice(0, story.length - 4)}';`)
  .join('\n');

const outputFilePath = path.resolve(`${__dirname}/../src/stories.ts`);

shelljs.mkdir('-p', path.dirname(outputFilePath));
fs.writeFileSync(
  outputFilePath,
  `// THIS FILE IS AUTOGENERATED
/* eslint-disable import/max-dependencies */
${files}
`,
);
shelljs.exec(`git add ${outputFilePath}`);
